use std::collections::{HashMap, VecDeque, HashSet};

use fields::{LargeFieldSer, ProtocolField};
use types::Replica;
use lambdaworks_math::field::element::FieldElement;

pub struct RandSharings<F: ProtocolField>{
    // Prepared-but-not-yet-dealt secret batches, in dispatch order (the vector
    // index is the ACSS/Sh2t instance id). We hold the raw secrets here and deal
    // them one batch at a time so that only ~1 ACSS/Sh2t instance is in flight per
    // module at a time, keeping peak memory bounded for large batch sizes.
    pub acss_pending: Vec<Vec<LargeFieldSer>>,
    pub sh2t_pending: Vec<Vec<LargeFieldSer>>,
    // Index of the next batch to dispatch for each module (also equals the number
    // already dispatched; the in-flight batch is `cursor - 1`).
    pub acss_dispatch_cursor: usize,
    pub sh2t_dispatch_cursor: usize,

    // First, add a map of sharings w.r.t. batch size and sender party
    // First map index is the sender party and the second map index is the batch number
    pub shares: HashMap<usize, HashMap<usize, Vec<FieldElement<F>>>>,
    // Also store the list of all parties whose ACSS completed
    pub acss_completed_parties: HashSet<usize>,
    // Second, add a map of 2t sharings of zero with the same indices
    pub sh2t_shares: HashMap<usize, HashMap<usize, Vec<FieldElement<F>>>>,
    // Store list of all parties who completed sh2t sharings
    pub sh2t_completed_parties: HashSet<usize>,
    // Third, store the ACS output values
    pub acs_output: HashSet<Replica>,
    // Fourth, store the random sharings generated by parties and the ACS set
    pub rand_sharings_inputs: (Vec<FieldElement<F>>, Vec<FieldElement<F>>),
    pub rand_sharings_mult: VecDeque<FieldElement<F>>,
    pub rand_2t_sharings_mult: VecDeque<FieldElement<F>>,

    // Fifth, set aside random sharings for coin tossing
    pub rand_sharings_coin: VecDeque<FieldElement<F>>,

    // Once-guard for `verify_termination`'s combine step. This is deliberately a
    // flag and not a length check on `rand_sharings_mult`: that vector is
    // `split_off` into `rand_sharings_coin` and drained by the multiplication
    // protocol, so its length says nothing about whether the combine already
    // ran. The flag is also set *before* the combine yields to rayon, so a
    // message processed during the yield re-enters `verify_termination` and
    // returns here instead of running preprocessing a second time.
    pub combine_started: bool
}

impl<F: ProtocolField> RandSharings<F>{
    pub fn new() -> Self{
        Self{
            acss_pending: Vec::new(),
            sh2t_pending: Vec::new(),
            acss_dispatch_cursor: 0,
            sh2t_dispatch_cursor: 0,
            shares: HashMap::default(),
            acss_completed_parties: HashSet::default(),
            sh2t_shares: HashMap::default(),
            sh2t_completed_parties: HashSet::default(),
            acs_output: HashSet::default(),
            rand_sharings_inputs: (Vec::new(), Vec::new()),
            rand_sharings_mult: VecDeque::new(),
            rand_2t_sharings_mult: VecDeque::new(),
            rand_sharings_coin: VecDeque::new(),
            combine_started: false
        }
    }
}