#!/usr/bin/env python3
"""Benchmark the Planner's operations on the local 10-party fixture.

For every (op, width, field) point this

  1. writes a `.arith` circuit of `k` gates of one type at one level, two
     input parties, every gate's output an output wire
     (testdata/circuits/bench/<op>_<k>.arith, git-ignored), and the two
     parties' input files with signed values inside every op's domain;
  2. runs it through scripts/test.sh (the `bristol_circuit` binary, hosted by
     the Planner) and waits for the syncer to report the output phase;
  3. reads the phase latencies off the syncer log, the plan off party 0's log
     (op-depths, engine depths, edaBits), the tuple count off the
     verification line, and the reconstructed outputs off every party;
  4. checks the outputs against an integer reference — exactly, except
     TRUNC/FMUL, which Liu et al.'s protocol computes to within ±2;

and appends one row per run to a CSV. Repetitions of a point are separate
rows; the report step takes medians.

    scripts/bench_ops.py run    [--reps 3] [--ks 1,64,1024,4096] [--fields m61base,m31base] [--ops ...] [--out logs/bench_ops.csv]
    scripts/bench_ops.py report [--out logs/bench_ops.csv]

Needs a release build of bristol_circuit and the testdata/10 fixture.
"""

import argparse
import csv
import os
import random
import re
import statistics
import subprocess
import sys
import time
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
N = 10
COMP = 10

# op name -> (gate token, arity). TRUNC/FMUL drop D bits.
D = 8
OPS = {
    "MUL": ("MUL", 2),
    "LT": ("LT", 2),
    "RELU": ("RELU", 1),
    "MAX": ("MAX", 2),
    "TRUNC": (f"TRUNC {D}", 1),
    "FMUL": (f"FMUL {D}", 2),
}
APPROX = {"TRUNC", "FMUL"}
# |inputs| < 2^13 keeps every op in domain at ℓ = 31 (|v|, |x·y| < 2^29).
BOUND = 1 << 13


def trunc(v, d):
    return v >> d if v >= 0 else -((-v) >> d)


def reference(op, a, b):
    if op == "MUL":
        return a * b
    if op == "LT":
        return int(a < b)
    if op == "RELU":
        return max(a, 0)
    if op == "MAX":
        return max(a, b)
    if op == "TRUNC":
        return trunc(a, D)
    if op == "FMUL":
        return trunc(a * b, D)
    raise ValueError(op)


def write_circuit(op, k):
    token, arity = OPS[op]
    path = os.path.join(ROOT, "testdata/circuits/bench", f"{op.lower()}_{k}.arith")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = [
        f"# {k} {token} gates at one level; generated by scripts/bench_ops.py",
        f"{k} {3 * k}",
        "2",
        f"{k} {k}",
        f"{k}",
        " ".join(str(2 * k + i) for i in range(k)),
        "",
    ]
    for i in range(k):
        if arity == 2:
            lines.append(f"2 1 {i} {k + i} {2 * k + i} {token}")
        else:
            lines.append(f"1 1 {i} {2 * k + i} {token}")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def write_inputs(k, seed):
    rng = random.Random(seed)
    a = [rng.randrange(-BOUND, BOUND) for _ in range(k)]
    b = [rng.randrange(-BOUND, BOUND) for _ in range(k)]
    for party, values in ((0, a), (1, b)):
        path = os.path.join(ROOT, f"testdata/inputs/circuit_input_{party}.txt")
        with open(path, "w") as f:
            f.write("\n".join(str(v) for v in values) + "\n")
    return a, b


APP_BINARIES = ["bristol_circuit", "anonymous_broadcast", "btx_setup", "reveal_probe"]


def kill_all():
    subprocess.run(["killall", "-9", *APP_BINARIES], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def launch_failed(label):
    """A party whose listener could not bind closes its networking layer
    within the first second — the port-reuse flake after a previous run."""
    for party in range(N):
        path = log_path(party, label)
        if os.path.exists(path) and "[mpc::context] Consensus error: Networking layer has closed" in open(path).read():
            return True
    return False


def log_path(party, label):
    return os.path.join(ROOT, "logs", f"party-{party}-n_{N}_{label}_{COMP}.log")


def syncer_path(label):
    return os.path.join(ROOT, "logs", f"syncer_n_{N}_{label}_{COMP}.log")


def phase_latencies(label):
    """Cumulative latency (ms) at the (n−t)-th party, per phase."""
    out = {}
    try:
        text = open(syncer_path(label)).read()
    except FileNotFoundError:
        return out
    for m in re.finditer(r'latency \[([0-9, ]+)\], status \{"(\w+)"\}', text):
        out[m.group(2)] = max(int(x) for x in m.group(1).split(","))
    return out


def run_point(op, k, field, rep, timeout, grace):
    label = f"{op}{k}{field}r{rep}"
    circuit = write_circuit(op, k)
    a, b = write_inputs(k, seed=zlib.crc32(f"{op}/{k}/{rep}".encode()))
    env = dict(os.environ, CIRCUIT=os.path.relpath(circuit, ROOT), FIELD=field)
    retries = 0
    while True:
        kill_all()
        time.sleep(20)  # sockets from the previous run have to close first
        subprocess.run(["bash", "scripts/test.sh", str(N), label, str(COMP)], cwd=ROOT, env=env,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(8)
        if not launch_failed(label) or retries == 3:
            break
        retries += 1
    start = time.time()
    phases = {}
    while time.time() - start < timeout:
        time.sleep(3)
        phases = phase_latencies(label)
        if "output" in phases:
            break
    time.sleep(grace)  # the syncer reports at n − t parties; let the stragglers finish
    kill_all()

    row = {"op": op, "k": k, "field": field, "rep": rep, "launch_retries": retries}
    p0 = open(log_path(0, label)).read() if os.path.exists(log_path(0, label)) else ""
    m = re.search(r"Planner: (\d+) op-depths over (\d+) engine depths, (\d+) edaBits \((\d+) random bits\)", p0)
    if m:
        row.update(op_depths=int(m.group(1)), rounds=int(m.group(2)), edabits=int(m.group(3)), planner_bits=int(m.group(4)))
    m = re.search(r"Initiating verification process for (\d+) multiplication tuples", p0)
    row["tuples"] = int(m.group(1)) if m else ""
    prev = 0
    for name, key in (("Preprocessing", "preprocessing_ms"), ("Online", "online_ms"),
                      ("verification", "verification_ms"), ("output", "output_ms")):
        if name in phases:
            row[key] = phases[name] - prev
            prev = phases[name]
        else:
            row[key] = ""
    row["total_ms"] = phases.get("output", "")

    # Every party's outputs, against the reference.
    want = [reference(op, x, y) for x, y in zip(a, b)]
    parties_out, max_err, mismatches = 0, 0, 0
    for party in range(N):
        path = log_path(party, label)
        if not os.path.exists(path):
            continue
        m = re.search(r"output wires reconstructed: \[([^\]]*)\]", open(path).read())
        if not m:
            continue
        parties_out += 1
        got = [int(x) for x in m.group(1).split(",")] if m.group(1).strip() else []
        if len(got) != k:
            mismatches += 1
            continue
        for g, w in zip(got, want):
            err = abs(g - w)
            max_err = max(max_err, err)
            if err > (2 if op in APPROX else 0):
                mismatches += 1
    row.update(parties_with_output=parties_out, max_abs_error=max_err, mismatches=mismatches,
               ba_coin_exhaustion=sum(open(log_path(p, label)).read().count("Coins unavailable")
                                      for p in range(N) if os.path.exists(log_path(p, label))))
    return row


FIELDS = ["op", "k", "field", "rep", "op_depths", "rounds", "edabits", "planner_bits", "tuples",
          "preprocessing_ms", "online_ms", "verification_ms", "output_ms", "total_ms",
          "parties_with_output", "max_abs_error", "mismatches", "ba_coin_exhaustion", "launch_retries"]


def cmd_run(args):
    out = os.path.join(ROOT, args.out)
    new = not os.path.exists(out)
    with open(out, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        if new:
            w.writeheader()
        for field in args.fields.split(","):
            for op in args.ops.split(","):
                for k in (int(x) for x in args.ks.split(",")):
                    for rep in range(args.reps):
                        row = run_point(op, k, field, rep, args.timeout, args.grace)
                        w.writerow(row)
                        f.flush()
                        print(" ".join(f"{key}={row.get(key, '')}" for key in FIELDS), flush=True)


def cmd_report(args):
    rows = list(csv.DictReader(open(os.path.join(ROOT, args.out))))
    groups = {}
    for r in rows:
        groups.setdefault((r["field"], r["op"], int(r["k"])), []).append(r)
    med = lambda rs, key: statistics.median(int(r[key]) for r in rs if r[key] not in ("", None)) if any(r[key] for r in rs) else None
    print("| field | op | k | rounds | edaBits | tuples | preprocessing | online | verification | output | runs ok |")
    print("|---|---|---|---|---|---|---|---|---|---|---|")
    for (field, op, k), rs in sorted(groups.items(), key=lambda g: (g[0][0], list(OPS).index(g[0][1]), g[0][2])):
        ok = sum(1 for r in rs if r["parties_with_output"] == str(N) and r["mismatches"] == "0")
        cell = lambda key: "—" if med(rs, key) is None else f"{med(rs, key):.0f}"
        print(f"| {field} | {op} | {k} | {rs[0]['rounds']} | {rs[0]['edabits']} | {rs[0]['tuples']} | "
              f"{cell('preprocessing_ms')} | {cell('online_ms')} | {cell('verification_ms')} | {cell('output_ms')} | {ok}/{len(rs)} |")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--reps", type=int, default=3)
    r.add_argument("--ks", default="1,64,1024,4096")
    r.add_argument("--fields", default="m61base,m31base")
    r.add_argument("--ops", default=",".join(OPS))
    r.add_argument("--timeout", type=int, default=600)
    r.add_argument("--grace", type=int, default=15, help="seconds to wait after the output phase before stopping the parties")
    r.add_argument("--out", default="logs/bench_ops.csv")
    q = sub.add_parser("report")
    q.add_argument("--out", default="logs/bench_ops.csv")
    args = p.parse_args()
    {"run": cmd_run, "report": cmd_report}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
