#!/usr/bin/env python3
"""Benchmark the erc20 application on the local 10-party fixture.

For every (transfers per epoch, epochs, field) point this

  1. writes a ledger of `T · E` transfers over `2T` accounts: senders
     0..T−1, each paying a receiver in T..2T−1 once per epoch, so every epoch
     holds exactly T transfers (a sender's next payment opens the next one);
  2. writes each party's input file — its accounts' balances in [0, 2^20),
     then its accounts' amounts, of which ~80 % are funded, ~10 % overdraw
     and ~10 % are negative (both must move nothing);
  3. runs the fixture (scripts/test.sh with APP_BIN=erc20), and reads the
     phase latencies, the plan and every party's final balances off the logs;
  4. checks the balances against the transfers run one by one in the clear;

and appends one row per run to a CSV. Launching, retrying and log parsing
are bench_ops.py's.

    scripts/bench_erc20.py run    [--reps 3] [--points 1x1,64x1,1024x1,4096x1,1024x4] [--fields m61base,m31base]
    scripts/bench_erc20.py report
"""

import argparse
import csv
import os
import random
import re
import statistics
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bench_ops  # noqa: E402  (launch, retry, log parsing)
from bench_ops import ROOT, N, COMP, kill_all, launch_failed, log_path, phase_latencies  # noqa: E402

bench_ops.APP_BINARIES.append("erc20")


def write_workload(t, epochs, seed):
    """The ledger file, the parties' input files, and the expected balances."""
    rng = random.Random(seed)
    accounts = 2 * t
    transfers = []
    for _ in range(epochs):
        receivers = list(range(t, 2 * t))
        rng.shuffle(receivers)
        transfers += list(zip(range(t), receivers))
    balances = [rng.randrange(0, 1 << 20) for _ in range(accounts)]

    # Amounts drawn against the balance the sender will have at that point.
    running = list(balances)
    amounts = []
    for sender, receiver in transfers:
        roll = rng.random()
        if roll < 0.1:
            amount = -rng.randrange(1, 1000)
        elif roll < 0.2:
            amount = running[sender] + rng.randrange(1, 1000)
        else:
            amount = rng.randrange(0, running[sender] + 1)
        amounts.append(amount)
        if 0 <= amount <= running[sender]:
            running[sender] -= amount
            running[receiver] += amount

    path = os.path.join(ROOT, "testdata/erc20/bench", f"{t}x{epochs}.ledger")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(f"# {t} transfers per epoch, {epochs} epochs; generated by scripts/bench_erc20.py\n")
        f.write(f"accounts {accounts}\n")
        f.writelines(f"{a} {b}\n" for a, b in transfers)
    for party in range(N):
        values = [balances[a] for a in range(accounts) if a % N == party]
        values += [x for (a, _), x in zip(transfers, amounts) if a % N == party]
        with open(os.path.join(ROOT, f"testdata/inputs/erc20_input_{party}.txt"), "w") as f:
            f.write("\n".join(str(v) for v in values) + "\n")
    return path, running


def run_point(t, epochs, field, rep, timeout, grace):
    label = f"erc20{t}x{epochs}{field}r{rep}"
    ledger, want = write_workload(t, epochs, seed=t * 1009 + epochs * 31 + rep)
    env = dict(os.environ, APP_BIN="erc20", APP_ARG=f"--ledger {os.path.relpath(ledger, ROOT)}", FIELD=field)
    retries = 0
    while True:
        kill_all()
        time.sleep(20)
        subprocess.run(["bash", "scripts/test.sh", str(N), label, str(COMP)], cwd=ROOT, env=env,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(8)
        if not launch_failed(label) or retries == 3:
            break
        retries += 1
    start = time.time()
    phases = {}
    while time.time() - start < timeout:
        time.sleep(3)
        phases = phase_latencies(label)
        if "output" in phases:
            break
    time.sleep(grace)
    kill_all()

    row = {"transfers_per_epoch": t, "epochs": epochs, "field": field, "rep": rep, "launch_retries": retries}
    p0 = open(log_path(0, label)).read() if os.path.exists(log_path(0, label)) else ""
    m = re.search(r"Planner: (\d+) op-depths over (\d+) engine depths, (\d+) edaBits", p0)
    if m:
        row.update(op_depths=int(m.group(1)), rounds=int(m.group(2)), edabits=int(m.group(3)))
    m = re.search(r"Initiating verification process for (\d+) multiplication tuples", p0)
    row["tuples"] = int(m.group(1)) if m else ""
    prev = 0
    for name, key in (("Preprocessing", "preprocessing_ms"), ("Online", "online_ms"),
                      ("verification", "verification_ms"), ("output", "output_ms")):
        row[key] = phases[name] - prev if name in phases else ""
        prev = phases.get(name, prev)
    row["total_ms"] = phases.get("output", "")
    parties_out, mismatches = 0, 0
    for party in range(N):
        path = log_path(party, label)
        if not os.path.exists(path):
            continue
        m = re.search(r"Erc20: \d+ final balances: \[([^\]]*)\]", open(path).read())
        if not m:
            continue
        parties_out += 1
        got = [int(x) for x in m.group(1).split(",")]
        mismatches += sum(1 for g, w in zip(got, want) if g != w) + abs(len(got) - len(want))
    row.update(parties_with_output=parties_out, mismatches=mismatches,
               ba_coin_exhaustion=sum(open(log_path(p, label)).read().count("Coins unavailable")
                                      for p in range(N) if os.path.exists(log_path(p, label))))
    return row


FIELDS = ["transfers_per_epoch", "epochs", "field", "rep", "op_depths", "rounds", "edabits", "tuples",
          "preprocessing_ms", "online_ms", "verification_ms", "output_ms", "total_ms",
          "parties_with_output", "mismatches", "ba_coin_exhaustion", "launch_retries"]


def cmd_run(args):
    out = os.path.join(ROOT, args.out)
    new = not os.path.exists(out)
    with open(out, "a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        if new:
            w.writeheader()
        for field in args.fields.split(","):
            for point in args.points.split(","):
                t, e = (int(x) for x in point.split("x"))
                for rep in range(args.reps):
                    row = run_point(t, e, field, rep, args.timeout, args.grace)
                    w.writerow(row)
                    f.flush()
                    print(" ".join(f"{k}={row.get(k, '')}" for k in FIELDS), flush=True)


def cmd_report(args):
    rows = list(csv.DictReader(open(os.path.join(ROOT, args.out))))
    groups = {}
    for r in rows:
        groups.setdefault((r["field"], int(r["transfers_per_epoch"]), int(r["epochs"])), []).append(r)
    med = lambda rs, k: statistics.median(int(r[k]) for r in rs if r[k]) if any(r[k] for r in rs) else None
    print("| field | transfers/epoch | epochs | rounds | edaBits | tuples | preprocessing | online | verification | output | total | runs ok |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for (field, t, e), rs in sorted(groups.items()):
        ok = sum(1 for r in rs if r["parties_with_output"] == str(N) and r["mismatches"] == "0")
        cell = lambda k: "—" if med(rs, k) is None else f"{med(rs, k):,.0f}"
        print(f"| {field} | {t} | {e} | {rs[0]['rounds']} | {rs[0]['edabits']} | {int(rs[0]['tuples'] or 0):,} | "
              f"{cell('preprocessing_ms')} | {cell('online_ms')} | {cell('verification_ms')} | {cell('output_ms')} | "
              f"{cell('total_ms')} | {ok}/{len(rs)} |")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--reps", type=int, default=3)
    r.add_argument("--points", default="1x1,64x1,1024x1,4096x1,1024x4", help="TxE: T transfers per epoch, E epochs")
    r.add_argument("--fields", default="m61base,m31base")
    r.add_argument("--timeout", type=int, default=900)
    r.add_argument("--grace", type=int, default=15)
    r.add_argument("--out", default="logs/bench_erc20.csv")
    q = sub.add_parser("report")
    q.add_argument("--out", default="logs/bench_erc20.csv")
    args = p.parse_args()
    {"run": cmd_run, "report": cmd_report}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
